version: '3.3'
services:
  judge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUPPETEER_BROWSER_PATH=/usr/bin/chromium-browser
        - PORT=8000
        - NODE_ENV=development
        - JUDGE_SERVICE_PATH=https://86fe98e7-458c-4715-b1cf-04facaa84232.mock.pstmn.io
    ports:
      - 8000:8000
