version: '3.3'
services:
  judge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUPPETEER_BROWSER_PATH=/usr/bin/chromium-browser
        - PORT=8000
        - NODE_ENV=development
    ports:
      - 8000:8000
