name: CI
on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Cache exercises
        uses: actions/cache@v3.0.1
        with:
          path: |
            exercises/**/projects
            exercises/exercise-lock.json
          key: v2-${{ runner.os }}
      - run: npm ci
      - run: npm run type-check
      - run: npm run build
      - name: Test core
        run: npm test --workspace @ftrprf/judge-core
      - name: Test runner
        run: npm test --workspace @ftrprf/judge-test-utils
      - name: Download exercises
        run: 'npm run ipm --workspace @ftrprf/ipm -- sync ${GITHUB_WORKSPACE}/exercises'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Test exercises
        run: 'npm run test:exercises'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run format:check
