name: Deploy to production
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release-tag:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set version variable
        run: |
          export VERSION="$(grep 'version' package.json | head -n 1 | cut -d '"' -f4 | tr -d '[[:space:]]')"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Authenticate using a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_PROD }}

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_REGISTRY_DOMAIN_PROD }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME_PROD }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD_PROD }}

      - name: Image tag name
        run: echo "tag_name=RELEASE-${{ env.version }}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_DOMAIN_PROD }}/scratch-judge:${{ env.tag_name }}

      - name: Update image tag on the Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'scratch-judge-prd'
          images: ${{ secrets.AZURE_REGISTRY_DOMAIN_PROD }}/scratch-judge:${{ env.tag_name  }}

      - name: Create release tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: RELEASE-v${{ env.version }}
          release_name: Release ${{ env.version  }}
          draft: false
          prerelease: false
